### ISSUE TITLE
Spinner & race conditions

### ISSUE THREAD

**Issue by rogosprojects** [rogosprojects/klogs#14]
In large cluster, with several containers, using `spinner` is unsafe in threads.
![image](https://github.com/user-attachments/assets/d487c295-8154-4ec9-adda-bad33a53eaef)

`pterm` is not thread safe due to race conditions.
Ref:
* https://github.com/pterm/pterm/pull/447
* https://github.com/pterm/pterm/issues/439
* https://github.com/pterm/pterm/issues/655
* https://github.com/pterm/pterm/issues/668

**Comment by davidecavestro** [comment]
IMHO the UI and streaming logic should be decoupled. In other discussions we talked about an auto-updating widget: I think it is the way forward.
A simple implementation could leverage - with [proper locking/coordination](https://pkg.go.dev/sync#Map) - a map or any other structure holding the current status for every processed pod/container/stream/file, concurrently updated by streaming threads and a dedicated go routine/thread with a loop polling current status to update the UI (hence avoiding race conditions).
An evolution could use channels to implement some sort of event loop or event pump.

Brainstorming:
- https://github.com/charmbracelet/bubbletea/tree/master/tutorials/commands/#the-update-method
- https://github.com/rivo/tview/wiki/Concurrency

**Comment by rogosprojects** [comment]
Sure! Give a look at the linked PR. I wrote a first decoupling tentative. 

I think it works well, but let's consider it like a starting point. 

Anyway, spinner (or any logic that tries to update Terminals) should be avoided when possible. They're terribile to manage.
